.PHONY: run build clean rebuild test package

# Executa aplicação JavaFX
run:
	mvn javafx:run

# Compila
build:
	mvn compile

# Executa testes
test:
	mvn test

# Gera jar
package:
	mvn clean package

# Limpa
clean:
	mvn clean

# Recompila tudo
rebuild:
	mvn clean javafx:run