version: '3.8'
services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "7777:7777"

volumes:
  db-data:
